spring:
  application:
    name: catalogo-produto-api
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  datasource:
    name: catalogo-produtos
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalogo-produtos?currentSchema=catalogo_produtos
    username: catalogo-produtos
    password: catalogo-produtos


jwt:
  secret: Xk8ufegFsO+TDlf43dyyK5SaaT0/8W4vgHPbCajymV3yCrSGXwv6dNI/EgKZZD46hT24I3aGmj/j+7RP1jMqtA==

server:
  port: 8080